config/routes.rb
Rails.application.routes.draw do

  resources :todos do
    resources :tasks
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo

  before_create :set_sequence
  before_validation :set_initial_sequence, on: :create
  before_validation :check_description

  default_scope { order(sequence: :asc) }

  def set_sequence
    return unless self.sequence.blank?
    self.sequence = self.todo.tasks.size
  end

  def check_description
    self.description = self.description if description.blank?
  end

  def adjust_sequence(new_sequence)
    todo = self.todo

    if self.sequence < new_sequence
      todo.tasks.where('sequence > ? AND sequence <= ?', self.sequence, new_sequence).each do |t|
        t.update(sequence: t.sequence - 1)
      end
    else
      todo.tasks.where('sequence >= ? AND sequence < ?', new_sequence, self.sequence).each do |t|
        t.update(sequence: t.sequence + 1)
      end
    end
  end

  def reorder_sequences_after_delete
    self.todo.tasks.where('sequence > ?', sequence).update_all('sequence = sequence - 1')
  end

  def set_initial_sequence
    self.sequence = Task.maximum(:sequence).to_i + 1
  end
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :set_todo#, only: %i[ show edit update destroy ]
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = @todo.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @todo.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = @todo.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to todo_tasks_url, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: todo_task_path(todo_id: @todo, id: @task) }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      @task.adjust_sequence(task_params[:sequence]) if task_params[:sequence]
      if @task.update(task_params)
        format.html { redirect_to todo_tasks_url(@todo), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    @task.reorder_sequences_after_delete
    respond_to do |format|
      format.html { redirect_to todo_tasks_url, notice: "Task was successfully destroyed." }
      format.json { render :delete, status: 200 }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @todo.tasks.find(params[:id])
    end

    def set_todo
      @todo = Todo.find(params[:todo_id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      # binding.pry
      params.require(:task).permit(:description, :sequence, :finished)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :finished)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, url: (params[:action] == 'edit' ? todo_task_path(todo_id: @todo) : todo_tasks_path)) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :finished, style: "display: block" %>
    <%= form.check_box :finished %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

  <p>
    <strong>Sequence:</strong>
    <%= task.sequence %>
  </p>

  <p>
    <strong>Finished:</strong>
    <%= task.finished %>
  </p>

  <p>
    <strong>Todo:</strong>
    <%= task.todo_id %>
  </p>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", todo_task_path(@task) %> |
  <%= link_to "Back to tasks", todo_tasks_path(@todo) %>
</div>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", todo_task_path(todo_id: @todo, id: task) %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_todo_task_path %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", todo_tasks_path(id: @todo) %>
</div>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<div>
  <%= link_to "Edit this task", edit_todo_task_path(todo_id: @todo, id: @task) %> |
  <%= link_to "Back to tasks", todo_tasks_path(@todo) %>

  <%= button_to "Destroy this task", todo_task_path(todo_id: @todo, id: @task), method: :delete %>
</div>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :finished, style: "display: block" %>
    <%= form.check_box :finished %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<div id="<%= dom_id todo %>">
  <p>
    <strong>Name:</strong>
    <%= todo.name %>
  </p>

  <p>
    <strong>Finished:</strong>
    <%= todo.finished %>
  </p>

  <p>
    <%= link_to 'Add Task', new_todo_task_path(todo_id: todo) %>
  </p>
</div>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Show this todo", @todo %> |
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Todos</h1>

<div id="todos">
  <% @todos.each do |todo| %>
    <%= render todo %>
    <p>
      <%= link_to "Show this todo", todo %>
    </p>
  <% end %>
</div>

<%= link_to "New todo", new_todo_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render "form", todo: @todo %>

<br>

<div>
  <%= link_to "Back to todos", todos_path %>
</div>

app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @todo %>

<div>
  <%= link_to "Edit this todo", edit_todo_path(@todo) %> |
  <%= link_to "Back to todos", todos_path %>

  <%= button_to "Destroy this todo", @todo, method: :delete %>
</div>